language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
    - REQUIREMENTS=bare
    - REQUIREMENTS=flask

install:
    - pip install -r .travis-$REQUIREMENTS-requirements.txt --use-mirrors

script: nosetests
